-- LDC Premises ETL - PostgreSQL Table Definitions
-- Created as part of HSDS pipeline integration
-- 
-- Tables:
--   1. ldc_premises_raw (57 columns) - Accumulated, deduplicated working data
--   2. ldc_premises_clean (38 columns) - Transformed output for analyst consumption
--   3. ldc_premises_staging (temporary) - Used for upsert operations

-- ============================================================================
-- TABLE 1: ldc_premises_raw (57 columns - working set only)
-- ============================================================================
-- Design Decision: Store only columns needed for transformations + clean output.
-- Full 195-column snapshots archived to S3 Parquet.
-- This table IS the accumulated "all_biz_raw" equivalent - it holds all
-- historical data plus monthly Snowflake upserts.

DROP TABLE IF EXISTS ldc_premises_raw CASCADE;

CREATE TABLE ldc_premises_raw (
    -- Primary key (composite for upsert)
    tenant_id BIGINT NOT NULL,
    premises_id BIGINT NOT NULL,
    date_create TIMESTAMP NOT NULL,

    -- Core fields (used in transformations)
    tenant VARCHAR(500),
    tenant_status VARCHAR(50),
    premises_status VARCHAR(50),
    category VARCHAR(200),
    category_id INTEGER,
    classification VARCHAR(100),
    classification_id INTEGER,
    subcategory VARCHAR(200),
    subcategory_id INTEGER,
    subcategory_previous VARCHAR(200),
    subcategory_previous_id INTEGER,

    -- Location
    address TEXT,
    building VARCHAR(300),
    street VARCHAR(200),
    street_number VARCHAR(50),
    unit_number VARCHAR(50),
    city VARCHAR(100),
    zip VARCHAR(20),
    geography VARCHAR(200),
    geography_id BIGINT,
    geography_large VARCHAR(200),
    geography_large_id BIGINT,
    geography_large_pct DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    uprn_id BIGINT,

    -- Property
    property VARCHAR(200),
    property_id BIGINT,
    property_type VARCHAR(100),
    premises_previous_id TEXT,

    -- Company
    company VARCHAR(500),
    company_id BIGINT,
    company_holding VARCHAR(500),
    company_holding_id BIGINT,
    tenant_care_of VARCHAR(500),
    flag_independent SMALLINT,
    flag_concession SMALLINT,
    flag_field_researched SMALLINT,
    flag_area_sm_modelled SMALLINT,

    -- Metrics
    area_sm DOUBLE PRECISION,
    voa_business_rate DOUBLE PRECISION,

    -- Contact
    phone VARCHAR(50),
    retail_mix VARCHAR(200),
    url_website TEXT,
    url_image TEXT,

    -- Dates
    date_close TIMESTAMP,
    date_premises_create TIMESTAMP,
    date_last_survey_field TIMESTAMP,
    date_last_survey_office TIMESTAMP,
    timestamp_create TIMESTAMP,
    timestamp_update TIMESTAMP,

    -- Metadata
    source VARCHAR(20) NOT NULL,
    row_hash VARCHAR(64),
    ingested_at TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY (tenant_id, premises_id, date_create)
);

-- Indexes for common query patterns
CREATE INDEX idx_ldc_raw_premises ON ldc_premises_raw(premises_id);
CREATE INDEX idx_ldc_raw_timestamp ON ldc_premises_raw(timestamp_update);
CREATE INDEX idx_ldc_raw_source ON ldc_premises_raw(source);
CREATE INDEX idx_ldc_raw_tenant_care_of ON ldc_premises_raw(tenant_care_of) WHERE tenant_care_of IS NOT NULL;
CREATE INDEX idx_ldc_raw_tenant ON ldc_premises_raw(tenant);
CREATE INDEX idx_ldc_raw_geography ON ldc_premises_raw(geography);
CREATE INDEX idx_ldc_raw_date_close ON ldc_premises_raw(date_close);
CREATE INDEX idx_ldc_raw_tenant_status ON ldc_premises_raw(tenant_status);

-- Add comments for documentation
COMMENT ON TABLE ldc_premises_raw IS 'LDC premises raw data - accumulated history with monthly Snowflake upserts (57 working columns)';
COMMENT ON COLUMN ldc_premises_raw.tenant_id IS 'LDC unique identifier for each tenancy/business instance';
COMMENT ON COLUMN ldc_premises_raw.premises_id IS 'LDC unique identifier for physical property location';
COMMENT ON COLUMN ldc_premises_raw.date_create IS 'Date when tenancy/business started at this location';
COMMENT ON COLUMN ldc_premises_raw.tenant_care_of IS 'Parent tenant for shop-within-shop (SWS) records';
COMMENT ON COLUMN ldc_premises_raw.source IS 'Data source: live (Snowflake), historic (Excel), archived (backups)';
COMMENT ON COLUMN ldc_premises_raw.row_hash IS 'Hash of all columns for change detection during upsert';


-- ============================================================================
-- TABLE 2: ldc_premises_clean (38 columns)
-- ============================================================================
-- Transformed output for analyst consumption. Generated by LdcPremisesTransform.
-- Uses BIGSERIAL surrogate PK instead of composite PK because
-- fix_premises_dates can produce rare legitimate SWS duplicates on
-- (tenant_id, premises_id, date_create) -- e.g. a main premises
-- and a concession sharing the same tenant_id.

DROP TABLE IF EXISTS ldc_premises_clean CASCADE;

CREATE TABLE ldc_premises_clean (
    id BIGSERIAL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    tenant VARCHAR(500),
    address TEXT,
    street VARCHAR(200),
    geography VARCHAR(200),
    zip VARCHAR(20),
    geography_large VARCHAR(200),
    uprn_id BIGINT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    premises_id BIGINT NOT NULL,
    property_id BIGINT,
    property VARCHAR(200),
    tenant_status VARCHAR(50),
    premises_status VARCHAR(50),
    company_id BIGINT,
    company VARCHAR(500),
    company_holding VARCHAR(500),
    tenant_care_of VARCHAR(500),
    flag_independent SMALLINT,
    category VARCHAR(200),
    classification VARCHAR(100),
    subcategory VARCHAR(200),
    phone VARCHAR(50),
    url_website TEXT,
    url_image TEXT,
    area_sm DOUBLE PRECISION,
    voa_business_rate DOUBLE PRECISION,
    date_create TIMESTAMP NOT NULL,
    date_close TIMESTAMP,
    date_last_survey_field TIMESTAMP,
    date_last_survey_office TIMESTAMP,
    date_premises_create TIMESTAMP,
    timestamp_create TIMESTAMP,
    timestamp_update TIMESTAMP,
    latest_record_check TIMESTAMP,
    latest_premises_check TIMESTAMP,
    source VARCHAR(20)
);

-- Indexes for analyst queries
CREATE INDEX idx_ldc_clean_premises ON ldc_premises_clean(premises_id);
CREATE INDEX idx_ldc_clean_tenant ON ldc_premises_clean(tenant);
CREATE INDEX idx_ldc_clean_geography ON ldc_premises_clean(geography);
CREATE INDEX idx_ldc_clean_geography_large ON ldc_premises_clean(geography_large);
CREATE INDEX idx_ldc_clean_classification ON ldc_premises_clean(classification);
CREATE INDEX idx_ldc_clean_category ON ldc_premises_clean(category);
CREATE INDEX idx_ldc_clean_tenant_status ON ldc_premises_clean(tenant_status);
CREATE INDEX idx_ldc_clean_date_create ON ldc_premises_clean(date_create);
CREATE INDEX idx_ldc_clean_date_close ON ldc_premises_clean(date_close);
CREATE INDEX idx_ldc_clean_coords ON ldc_premises_clean(latitude, longitude);

-- Add comments for documentation
COMMENT ON TABLE ldc_premises_clean IS 'LDC premises clean data - 38 columns for analyst consumption. BIGSERIAL PK to accommodate rare SWS duplicates on (tenant_id, premises_id, date_create)';
COMMENT ON COLUMN ldc_premises_clean.latest_record_check IS 'Latest of date_last_survey_field or date_last_survey_office';
COMMENT ON COLUMN ldc_premises_clean.latest_premises_check IS 'Max latest_record_check for all records at this premises_id';


-- ============================================================================
-- TABLE 3: ldc_premises_staging (temporary for upsert)
-- ============================================================================
-- Unlogged table for faster staging during upsert operations.
-- Schema matches ldc_premises_raw for seamless INSERT...ON CONFLICT.

DROP TABLE IF EXISTS ldc_premises_staging CASCADE;

CREATE UNLOGGED TABLE ldc_premises_staging (
    LIKE ldc_premises_raw INCLUDING ALL
);

COMMENT ON TABLE ldc_premises_staging IS 'Temporary staging table for upsert operations (unlogged for speed)';


-- ============================================================================
-- GRANT PERMISSIONS (adjust as needed for your environment)
-- ============================================================================
-- GRANT SELECT ON ldc_premises_raw TO readonly_role;
-- GRANT SELECT ON ldc_premises_clean TO readonly_role;
-- GRANT ALL ON ldc_premises_raw TO etl_role;
-- GRANT ALL ON ldc_premises_clean TO etl_role;
-- GRANT ALL ON ldc_premises_staging TO etl_role;
